# -*- coding: utf-8 -*-
"""Sistema de Turnos para Atención Estudiantil

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEj7Gda6U0Z_0Kw91vgEvmWGebYWVCy_
"""

class ColaTurnos:
    def __init__(self, capacidad):
        self.capacidad = capacidad
        self.vector = [None] * capacidad
        self.frente = 0
        self.final = 0

    def esta_vacia(self):
        return self.frente == self.final

    def esta_llena(self):
        return self.final == self.capacidad

    def encolar(self, estudiante):
        if self.esta_llena():
            print("La cola está llena. No se puede agregar otro estudiante.")
            return False

        self.vector[self.final] = estudiante
        self.final += 1

        print(
            f"Estudiante agregado: {estudiante['nombre']} "
            f"(Turno {estudiante['turno']})"
        )
        return True

    def desencolar(self):
        if self.esta_vacia():
            print("La cola está vacía. No hay estudiantes para atender.")
            return None

        estudiante = self.vector[self.frente]
        self.vector[self.frente] = None
        self.frente += 1

        print(
            f"Atendiendo a: {estudiante['nombre']} "
            f"(Turno {estudiante['turno']})"
        )

        return estudiante

    def consultar_frente(self):
        if self.esta_vacia():
            print("La cola está vacía.")
            return None

        estudiante = self.vector[self.frente]

        print(
            f"Siguiente estudiante: {estudiante['nombre']} "
            f"(Turno {estudiante['turno']})"
        )

        return estudiante

    def mostrar(self):
        if self.esta_vacia():
            print("No hay estudiantes esperando.")
            return

        print("\n--- ESTUDIANTES EN ESPERA ---")

        for i in range(self.frente, self.final):
            estudiante = self.vector[i]

            print(
                f"Posición {i}: "
                f"Turno {estudiante['turno']} - "
                f"{estudiante['nombre']} - "
                f"{estudiante['motivo']}"
            )

        print("-----------------------------")


def crear_estudiante(turno, nombre, motivo):
    return {
        "turno": turno,
        "nombre": nombre,
        "motivo": motivo
    }


def caso_normal():

    print("       CASO NORMAL")


    cola = ColaTurnos(5)

    estudiante1 = crear_estudiante(
        1, "Ana", "Matrícula"
    )

    estudiante2 = crear_estudiante(
        2, "Carlos", "Certificado"
    )

    estudiante3 = crear_estudiante(
        3, "Laura", "Actualización de datos"
    )

    cola.encolar(estudiante1)
    cola.encolar(estudiante2)
    cola.encolar(estudiante3)

    cola.mostrar()

    print("\nConsulta del frente:")
    cola.consultar_frente()

    print("\nAtención:")
    cola.desencolar()

    cola.mostrar()


def caso_limite():

    print("        CASO LÍMITE")


    cola = ColaTurnos(3)

    estudiante1 = crear_estudiante(
        1, "Ana", "Matrícula"
    )

    estudiante2 = crear_estudiante(
        2, "Carlos", "Certificado"
    )

    estudiante3 = crear_estudiante(
        3, "Laura", "Actualización de datos"
    )

    estudiante4 = crear_estudiante(
        4, "Pedro", "Información académica"
    )

    print("\nLlenando la cola:")

    cola.encolar(estudiante1)
    cola.encolar(estudiante2)
    cola.encolar(estudiante3)

    cola.mostrar()

    print("\nIntentando agregar un cuarto estudiante:")
    cola.encolar(estudiante4)

    print("\nAtendiendo estudiantes:")
    cola.desencolar()
    cola.desencolar()
    cola.desencolar()

    print("\nIntentando atender cuando la cola está vacía:")
    cola.desencolar()


def main():

    print(" SISTEMA DE TURNOS PARA ATENCIÓN ESTUDIANTIL")


    caso_normal()
    caso_limite()


if __name__ == "__main__":
    main()